[workspace]
members = ["crates/*"]
resolver = "2"

# Enable a small amount of optimization in the dev profile.
[profile.dev]
opt-level = 1


# Enable a large amount of optimization in the dev profile for dependencies.
[profile.dev.package."*"]
opt-level = 3

[patch.crates-io]
# Custom optimization or last minute upstream changes may be useful.
# rapier3d = { path = "../rapier/crates/rapier3d" }
# This branch contains a hack fix to angular interpolation, which seems to be wrongly computed?
rapier3d = { path = "../rapier/crates/rapier3d" }
parry3d = { path = "../parry/crates/parry3d" }
encase = { path = "../encase" }

bevy_rapier3d = { git = "https://github.com/dimforge/bevy_rapier.git", rev = "a4e9343cd75ce2be788280de2c21ed7efb9039b7" }