[package]
name = "sandbox"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenvy = "0.15"
bevy = { version = "0.15", features = [
    "multi_threaded",
    "jpeg",
    # Optional for iteration times,
    # see https://bevyengine.org/learn/quick-start/getting-started/setup/#enable-fast-compiles-optional
    "dynamic_linking",
    "serialize",
] }
bevy_math = { version = "0.15", features = ["rand"] }
bevy_editor_cam = "0.5.0"
bevy_rapier3d = "0.28"
map_def = { path = "../map_def" }
# bevy is on rand 0.8
rand = "0.8.0"
# bevy is on rand_chacha 0.3
rand_chacha = "0.3.1"
