[package]
name = "shared_map"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.15", features = ["serialize"] }
bevy_rapier3d = "0.28"
thiserror = "2.0"
serde = { version = "1", features = ["derive"] }
ron = "0.8"
